/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fish.glb 
Author: nottodayrender (https://sketchfab.com/nottodayrender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/koi-boy-3d-character-in-handpainted-style-8811c961c2e7492db591aa2a676eb224
Title: 🐟⭐🍎Koi Boy | 3D Character in Handpainted style
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fish.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Koi_001} position={[-1.588, 3.953, 0.031]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Koi_001} position={[-1.588, 3.981, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Koi_001} position={[-1.588, 3.256, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Koi_001} position={[-1.588, 3.256, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Koi_001} position={[-1.588, 3.256, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Koi_001} position={[-1.588, 3.256, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Koi_001} position={[-1.074, 0.463, -0.05]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Koi_001} position={[-1.588, 3.253, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Koi_001} position={[-2.173, 5.526, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Koi_001} position={[-2.17, 5.512, 0.005]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Koi_001} position={[-1.488, 3.248, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Koi_001} position={[-1.053, 0.4, 0.004]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Koi_001} position={[-1.588, 2.159, -1.393]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Koi_001} position={[-1.617, 3.886, 0.839]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Koi_001} position={[-1.588, 6.236, -1.134]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Koi_001} position={[-1.172, 0.463, -0.036]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Koi_001} position={[1.959, 0.463, -0.036]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Koi_001.001']} position={[1.577, 3.953, 0.031]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Koi_001.001']} position={[1.577, 3.981, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Koi_001.001']} position={[1.577, 3.256, 0]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Koi_001.001']} position={[1.577, 3.256, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['Koi_001.001']} position={[1.577, 3.256, 0]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Koi_001.001']} position={[1.577, 3.256, 0]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Koi_001.001']} position={[2.092, 0.463, -0.05]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['Koi_001.001']} position={[1.577, 3.253, 0]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Koi_001.001']} position={[0.992, 5.526, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials['Koi_001.001']} position={[0.995, 5.512, 0.005]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['Koi_001.001']} position={[1.678, 3.248, 0]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['Koi_001.001']} position={[2.112, 0.4, 0.004]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Koi_001.001']} position={[1.577, 2.159, -1.393]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['Koi_001.001']} position={[1.548, 3.886, 0.839]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Koi_001.001']} position={[1.577, 6.236, -1.134]} />
    </group>
  )
}

useGLTF.preload('/fish.glb')
